name: Build and Test Pipeline
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Test-and-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Test with Maven
        working-directory: ./JHotDraw
        run: mvn test 

      - name: Build with Maven
        working-directory: ./JHotDraw
        run: mvn --batch-mode --update-snapshots verify 
